name: mtihani_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.8.0+1
  encrypt_shared_preferences: ^0.8.8
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  internet_connection_checker: ^3.0.1
  intl: ^0.18.0
  jwt_decoder: ^2.0.1
  lottie: ^3.2.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  font_awesome_flutter: ^10.8.0
  csv: ^6.0.0
  file_picker: ^10.0.0
  universal_html: ^2.2.4
  fl_chart: ^0.63.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - google_fonts/

